# This workflow will IF changes are detected in the following folders: simulation, test, requirements.txt, .github/workflows,
# run lint and run unittests for python 3.10 and 3.10, with and without orjson
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application

on:
  pull_request:
    branches: 
      - main
      - devops

permissions:
  contents: read
  pull-requests: read

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2.11.1
      id: filter
      with:
        filters: |
          test:
            - 'test/**'
          simulation:
            - 'simulation/**'
          requirements:
            - 'requirements.txt'
          workflow:
            - '.github/workflows/*'

  build:
    needs: changes
    # Only run if critical changes were detected
    if: ${{ needs.changes.outputs != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: restore 
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
    # installs requirements.txt but NOT orjson
      run: |
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r <(grep -vE '\<orjson\>' requirements.txt); fi
    
    - name: Save cache
      uses: actions/cache/save@v3
      id: save-cache
      with:
        path: ~/.cache/pip
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run unittests without orjson
      run: |
        python -m unittest discover
    - name: Run unittests with orjson
    # this could be changed to only run tests which loads the json file?
      run: |
        pip install orjson
        python -m unittest discover